### PR TITLE
Upgrade pdf2htmlEX-Android to 0.18.25 to workaround issue #348

### PR DESCRIPTION
**Pull request by ViliusSutkus89**

### CODE REVIEW

**Comment by TomTasche** [comment]
I guess I should have tested that before merging: the problematic PDFs I sent you open completely empty for me when testing inside the app :thinking: @ViliusSutkus89

**Comment by ViliusSutkus89** [comment]
That sounds bad. I've tested the change on the library, then tested my own downstream app (Documenter) with the new library version and it was OK. Let me see what's what

**Comment by ViliusSutkus89** [comment]
Just did a clean build of odr.droid@main, all three documents look nice. I mean, font could look better, boldness is gone, but all the text is visible. Could you do a clean build to verify?

**Comment by TomTasche** [comment]
I definitely did, but will try again. Sorry!

**Comment by TomTasche** [comment]
I had to uninstall the app first, then it worked. I'm hoping that's just some Android Studio annoyance. All good, thanks! :+1:

**Pull request merged**
